// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    __Dialog__: typeof import('./src/views/demo/guide/__Dialog__.vue')['default']
    __Guide__: typeof import('./src/views/demo/guide/__Guide__.vue')['default']
    __mask__: typeof import('./src/views/demo/guide/__mask__.vue')['default']
    __popover__: typeof import('./src/views/demo/guide-copy/__popover__.vue')['default']
    __Popover__: typeof import('./src/views/demo/guide/__Popover__.vue')['default']
    __Popover2__: typeof import('./src/views/demo/guide/__Popover2__.vue')['default']
    404: typeof import('./src/views/404/index.vue')['default']
    AliveRouterView: typeof import('./src/components/AliveRouterView.vue')['default']
    Decimal: typeof import('./src/views/docs/utils/decimal.md')['default']
    Decimal_js: typeof import('./src/views/tools/math/decimal_js/index.vue')['default']
    Demo: typeof import('./src/views/demo.vue')['default']
    Docs: typeof import('./src/views/docs.vue')['default']
    Gojuon: typeof import('./src/views/tools/jp/gojuon/index.vue')['default']
    Guide: typeof import('./src/views/demo/guide/index.vue')['default']
    GuideCopy: typeof import('./src/views/demo/guide-copy/index.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    I18n: typeof import('./src/views/demo/i18n/index.vue')['default']
    InitProject: typeof import('./src/views/docs/config/init-project.md')['default']
    Loading: typeof import('./src/views/demo/animations/loading/index.vue')['default']
    LocalInputDecimal: typeof import('./src/components/LocalInputDecimal/index.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NMenu: typeof import('naive-ui')['NMenu']
    NScrollbar: typeof import('naive-ui')['NScrollbar']
    PatchPackage: typeof import('./src/views/docs/config/patch-package.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SpaceAnalyticGeometry: typeof import('./src/views/docs/maths/Space-Analytic-Geometry.md')['default']
    TableWidthResize: typeof import('./src/views/demo/TableWidthResize/index.vue')['default']
    Tools: typeof import('./src/views/tools.vue')['default']
    Undefined: typeof import('./src/views/index.vue')['default']
    Xicon: typeof import('./src/views/demo/xicon/index.vue')['default']
  }
}

export {}
